using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace OblivionInteractionIconsForwarder
{
    public static class Program
    {
        private class MySettings
        {
            public bool VerboseLogging { get; set; } = false;
        }
        
        private static Lazy<MySettings> _settings = null!;
        
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddRunnabilityCheck(CheckRunnability)
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "skymojibase-patcher.esp")
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out _settings)
                .Run(args);
        }

        private static void CheckRunnability(IRunnabilityState state)
        {
            state.LoadOrder.AssertListsMod("skymojibase.esl");
        }

        private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            var baseModEntry = state.LoadOrder.TryGetValue(new ModKey("skymojibase", ModType.Light));
            if (baseModEntry?.Mod == null)
            {
                if (_settings.Value.VerboseLogging)
                {
                    Console.WriteLine("This patcher requires a light mod named 'skymojibase.esl'.");
                }

                return;
            }

            var baseMod = baseModEntry.Mod;
            
            Console.WriteLine("Patching Activators");
            foreach (var activator in state.LoadOrder.PriorityOrder.WinningOverrides<IActivatorGetter>())
            {
                var referenceActivator = baseMod.Activators.TryGetValue(activator.FormKey);
                if (referenceActivator == null)
                {
                    if (_settings.Value.VerboseLogging)
                    {
                        Console.WriteLine($"Skipping record {activator.FormKey} - not relevant for this mod.");
                    }

                    continue;
                }

                if (referenceActivator.ActivateTextOverride == null || Equals(referenceActivator.ActivateTextOverride, activator.ActivateTextOverride))
                {
                    if (_settings.Value.VerboseLogging)
                    {
                        Console.WriteLine($"No patch needed for record {activator.FormKey}");
                    }

                    continue;
                }

                var modifiedActivator = state.PatchMod.Activators.GetOrAddAsOverride(activator);
                modifiedActivator.ActivateTextOverride = referenceActivator.ActivateTextOverride.DeepCopy();
                Console.WriteLine($"Patching {activator.ActivateTextOverride} with {referenceActivator.ActivateTextOverride}");
            }
            
            Console.WriteLine("Patching Flora");
            foreach (var flora in state.LoadOrder.PriorityOrder.WinningOverrides<IFloraGetter>())
            {
                var referenceFlora = baseMod.Florae.TryGetValue(flora.FormKey);
                if (referenceFlora == null)
                {
                    if (_settings.Value.VerboseLogging)
                    {
                        Console.WriteLine($"Skipping record {flora.FormKey} - not relevant for this mod.");
                    }

                    continue;
                }
                
                if (referenceFlora.ActivateTextOverride == null || Equals(referenceFlora.ActivateTextOverride, flora.ActivateTextOverride))
                {
                    if (_settings.Value.VerboseLogging)
                    {
                        Console.WriteLine($"No patch needed for record {flora.FormKey}");
                    }

                    continue;
                }

                var modifiedFlora = state.PatchMod.Florae.GetOrAddAsOverride(flora);
                modifiedFlora.ActivateTextOverride = referenceFlora.ActivateTextOverride.DeepCopy();
                Console.WriteLine($"Patching {flora.ActivateTextOverride} with {referenceFlora.ActivateTextOverride}");
            }
            
            Console.WriteLine("Done.");
        }
    }
}
